### ISSUE TITLE
feature suggest .sdf export

### ISSUE THREAD

**Issue by nbehrnd** [xuguodong1999/COCR#1]
While your repository shows _parts_ of the project only, is your program capable to export the structures as a .sdf / .mol2 file?  Would it be possible for you to use commit messages in English -- need not be perfect -- to widen the audience to people not capable to understand one of China's languages?

**Comment by xuguodong1999** [comment]
Currently I use rdkit and openbabel as a solution for chemistry-related functions, so multi-format export is possible and easy to add. It will be included in a next update.

**Comment by nbehrnd** [comment]
Based on the screen cast, this looks very nice.  The service the program provides bears similarities to [OSRA](https://cactus.nci.nih.gov/cgi-bin/osra/index.cgi) hosted by the U.S. American NIH national cancer institute ([background](https://cactus.nci.nih.gov/osra/)).
